repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
      - id: ruff-format
        name: ruff (format)
  - repo: local
    hooks:
      - id: clippy
        name: clippy (workspace, all targets, features)
        entry: cargo clippy --workspace --all-targets --all-features
        language: system
        types: [rust]
        pass_filenames: false
      - id: rustfmt
        name: rustfmt (check)
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: rustfmt-fix
        name: rustfmt (auto-fix)
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
        stages: [manual]
