###############################################################################
# cargo-make tasks
#
# Usage:
#   cargo make diagrams           # generate all diagrams
#   cargo make diagram-algorithm  # generate the algorithm diagram only
#
# This uses mermaid-cli (mmdc). If you don't have it installed, the task will
# try to use npx to run @mermaid-js/mermaid-cli without a global install.
###############################################################################

[config]
skip_core_tasks = true

[tasks.default]
description = "Generate diagrams (default task)"
category = "Documentation"
dependencies = ["diagrams"]

[tasks.diagrams]
description = "Generate all diagrams (SVG, transparent)"
category = "Documentation"
dependencies = ["diagram-algorithm"]

[tasks.diagram-algorithm]
description = "Render diagrams/algorithm.mmd -> assets/algorithm.svg"
category = "Documentation"
script_runner = "bash"
script = [
    """
    set -euo pipefail
    echo "[diagram] generating docs/assets/algorithm.svg from docs/diagrams/algorithm.mmd"
    mkdir -p docs/assets
    if ! command -v npx >/dev/null 2>&1; then
      echo "Error: 'npx' not found. Please install Node.js (which provides npx)." >&2
      exit 1
    fi
    npx -y @mermaid-js/mermaid-cli@10 mmdc -i docs/diagrams/algorithm.mmd -o docs/assets/algorithm.svg --backgroundColor transparent --configFile docs/diagrams/mermaid.config.json --cssFile docs/diagrams/mermaid.css
    test -s docs/assets/algorithm.svg || { echo "Error: docs/assets/algorithm.svg not generated" >&2; exit 1; }
    if command -v node >/dev/null 2>&1; then
      node docs/diagrams/postprocess.js docs/assets/algorithm.svg || echo "[diagram] postprocess skipped/failed, continuing"
    else
      echo "[diagram] node not found; skipping SVG post-process for layering"
    fi
    echo "[diagram] generated docs/assets/algorithm.svg"
    """,
]
