[package]
name = "headson-python"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "headson"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
pyo3 = { version = "0.22", features = ["extension-module"] }
headson = { path = ".." }

