name: Security Audit

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"  # Weekly, Mondays at 06:00 UTC

jobs:
  cargo-audit:
    name: cargo-audit (RustSec)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Deny warnings (e.g., yanked) in addition to vulnerabilities
          args: --deny warnings
