name: Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    name: Build and test (deny warnings)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Build all targets
        run: cargo build --all-targets --all-features

      - name: Run tests
        run: cargo test --all-targets --all-features
