name: Clippy

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy (all+perf+cargo, deny warnings)
        run: cargo clippy --all-targets --all-features -- -W clippy::all -W clippy::perf -W clippy::cargo -D warnings
