name: Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Compute coverage (summary + lcov)
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --summary-only

      - name: Generate HTML report (no re-run)
        run: |
          cargo llvm-cov --all-features --workspace --no-run --html

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: rust
          fail_ci_if_error: true
          verbose: true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: target/llvm-cov/html

      - name: Upload lcov.info
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: lcov.info
