name: Rustfmt

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable) with rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Verify rustfmt (79 cols)
        run: cargo fmt --all -- --check
